FROM golang:1.26 AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /aep-server ./cmd/aep-server/

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /aep-server /aep-server
EXPOSE 9091
ENTRYPOINT ["/aep-server"]
