apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-configs
  namespace: {{ .Release.Namespace }}
data:
  THUNDER_ADMIN_URL: {{ .Values.thunder.adminURL | quote }}
  THUNDER_JWKS_URL: {{ .Values.thunder.jwksURL | quote }}
  THUNDER_ISSUER: {{ .Values.console.thunderPublicURL | quote }}
  PLATFORM_API_SERVICE_BASE_URL: {{ .Values.aepApi.publicURL | quote }}
