/**
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  Avatar,
  AvatarGroup,
  Box,
  Chip,
  Divider,
  IconButton,
  Stack,
  Tooltip,
  Typography,
} from "@wso2/oxygen-ui";
import {
  ExternalLink,
  Sparkles,
  SquarePen,
  X as XIcon,
} from "@wso2/oxygen-ui-icons-react";
import { useNavigate } from "@tanstack/react-router";
import { useStickToBottom } from "use-stick-to-bottom";
import { useAgentChat } from "../useAgentChat";
import { useCurrentAuthor } from "../currentUser";
import { buildFeed, participantsOf, type FeedBlock } from "../feed";
import { MessageList } from "./MessageList";
import { ChatInput } from "./ChatInput";
import {
  buildDesignGenerationInstruction,
  buildSpecGenerationInstruction,
} from "@aep/contracts/prompts";
import { readCreatePrompt } from "../../projects/lib/promptStore";

// Default a touch wider than the old 380 so the activity rail + narration
// breathe; the user can drag-resize and the choice persists.
const AGENT_CHAT_PANEL_WIDTH = 440;
const MIN_WIDTH = 360;
const MAX_WIDTH = 720;
const WIDTH_STEP = 24; // keyboard resize increment
const WIDTH_KEY = "aep.chat.panelWidth";

// Empty-state starter prompts — one click prefills the composer (mirrors
// ProjectCreate's example-prompt pattern, scaled to a chip).
const SUGGESTIONS = [
  "Draft the requirements for this project",
  "Add acceptance criteria to the spec",
  "Add a returns-policy section",
] as const;

const clampWidth = (n: number): number =>
  Math.min(MAX_WIDTH, Math.max(MIN_WIDTH, Math.round(n)));

function initialOf(name: string): string {
  return name.trim().charAt(0).toUpperCase() || "?";
}

// The generation instruction for a one-shot signal: design is derived from the
// current requirements; requirements are seeded from the stored create prompt.
function instructionFor(
  signal: "requirements" | "design",
  org: string,
  projectName: string,
): string {
  return signal === "design"
    ? buildDesignGenerationInstruction()
    : buildSpecGenerationInstruction(readCreatePrompt(org, projectName));
}

// The project AI panel (#130), reworked into a multi-user activity stream
// (task 3): the header, scroll region, and composer live here; feed rendering
// and the turn/step split live in their own components.
export function AgentChatPanel({
  org,
  projectName,
  displayName,
  onClose,
  autoGenerate,
  onAutoGenerated,
}: {
  org: string;
  projectName: string;
  displayName?: string | undefined;
  onClose: () => void;
  /** Generation CTA (#150 spec / #159 design): auto-send the matching turn
   *  once — requirements seeded from the stored create prompt, design derived
   *  from the current requirements. */
  autoGenerate?: "requirements" | "design";
  /** Called after the auto-send fires, so the caller can clear the signal. */
  onAutoGenerated?: () => void;
}) {
  const { messages, isSending, activeTurnId, send, newConversation } = useAgentChat(
    org,
    projectName,
  );
  const author = useCurrentAuthor();
  const navigate = useNavigate();
  const [draft, setDraft] = useState("");

  const feed = useMemo(
    () => buildFeed(messages, { currentUserId: author.id, activeTurnId }),
    [messages, author.id, activeTurnId],
  );
  const participants = useMemo(
    () => participantsOf(messages, author.id),
    [messages, author.id],
  );

  // A teammate's running turn locks the composer (a concurrent send 409s
  // anyway — this makes the lock legible rather than surprising).
  const runningTurn = feed.find(
    (b): b is Extract<FeedBlock, { kind: "turn" }> =>
      b.kind === "turn" && b.status === "running",
  );
  const teammateRunning =
    runningTurn && !runningTurn.attribution.isOwn
      ? runningTurn.attribution.displayName
      : null;
  const inputDisabled = isSending || Boolean(teammateRunning);
  const hint = teammateRunning
    ? `Agent is working on ${teammateRunning}'s request…`
    : null;
  // Before a turn has emitted anything it has no block yet — show a tail
  // "Working…" so a send never looks dropped.
  const showWorkingTail =
    isSending && !feed.some((b) => b.kind === "turn" && b.status === "running");

  // Same-file tool runs render collapsed by default; a click flips membership.
  const [expandedGroups, setExpandedGroups] = useState<Set<string>>(() => new Set());
  const toggleGroup = useCallback((id: string) => {
    setExpandedGroups((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  // Follow the streaming tail (breaks the lock if the user scrolls up).
  const { scrollRef, contentRef } = useStickToBottom();

  const openSpec = useCallback(() => {
    void navigate({
      to: "/projects/$projectName/spec",
      params: { projectName },
    });
  }, [navigate, projectName]);

  // --- Drag-to-resize (persisted) --------------------------------------
  const [width, setWidth] = useState<number>(() => {
    try {
      const raw = localStorage.getItem(WIDTH_KEY);
      const n = raw ? Number.parseInt(raw, 10) : Number.NaN;
      if (Number.isFinite(n)) return clampWidth(n);
    } catch {
      // fall through to default
    }
    return AGENT_CHAT_PANEL_WIDTH;
  });
  const [dragging, setDragging] = useState(false);
  const dragRef = useRef<{ startX: number; startW: number } | null>(null);
  useEffect(() => {
    if (!dragging) return;
    const onMove = (e: MouseEvent) => {
      const d = dragRef.current;
      if (d) setWidth(clampWidth(d.startW + (d.startX - e.clientX)));
    };
    const onUp = () => setDragging(false);
    window.addEventListener("mousemove", onMove);
    window.addEventListener("mouseup", onUp);
    return () => {
      window.removeEventListener("mousemove", onMove);
      window.removeEventListener("mouseup", onUp);
    };
  }, [dragging]);
  useEffect(() => {
    try {
      localStorage.setItem(WIDTH_KEY, String(width));
    } catch {
      // width persistence is best-effort
    }
  }, [width]);

  // --- One-shot generate (#150 spec / #159 design) ---------------------
  // Fire exactly once per signal, re-arm on clear so a later Generate click
  // fires again. `send` is held in a ref and kept out of the deps: its identity
  // flips whenever `isSending` changes, which would otherwise re-run this
  // mid-turn. See the original panel note (#150) for the full rationale.
  const sendRef = useRef(send);
  sendRef.current = send;
  const autoGenFiredRef = useRef(false);
  useEffect(() => {
    if (!autoGenerate) {
      autoGenFiredRef.current = false;
      return;
    }
    if (autoGenFiredRef.current) return;
    autoGenFiredRef.current = true;
    sendRef.current(instructionFor(autoGenerate, org, projectName));
    onAutoGenerated?.();
  }, [autoGenerate, org, projectName, onAutoGenerated]);

  const submit = () => {
    if (!draft.trim() || inputDisabled) return;
    send(draft);
    setDraft("");
  };

  const onNewConversation = () => {
    if (isSending) return;
    newConversation();
    setDraft("");
  };

  return (
    <Box
      sx={{
        position: "relative",
        width,
        flexShrink: 0,
        height: "100%",
        display: "flex",
        flexDirection: "column",
        borderLeft: 1,
        borderColor: "divider",
        bgcolor: "background.paper",
      }}
    >
      {/* Drag handle on the left edge. */}
      <Box
        role="separator"
        aria-orientation="vertical"
        aria-label="Resize agent panel"
        aria-valuenow={width}
        aria-valuemin={MIN_WIDTH}
        aria-valuemax={MAX_WIDTH}
        tabIndex={0}
        onMouseDown={(e) => {
          dragRef.current = { startX: e.clientX, startW: width };
          setDragging(true);
          e.preventDefault();
        }}
        onKeyDown={(e) => {
          if (e.key === "ArrowLeft") setWidth((w) => clampWidth(w + WIDTH_STEP));
          else if (e.key === "ArrowRight") setWidth((w) => clampWidth(w - WIDTH_STEP));
        }}
        sx={{
          position: "absolute",
          left: 0,
          top: 0,
          bottom: 0,
          width: 6,
          ml: "-3px",
          cursor: "col-resize",
          zIndex: 1,
          "&:hover, &:focus-visible": { bgcolor: "primary.main", opacity: 0.4 },
          ...(dragging ? { bgcolor: "primary.main", opacity: 0.4 } : {}),
        }}
      />

      {/* Header */}
      <Stack
        direction="row"
        spacing={1}
        sx={{ alignItems: "center", px: 2, py: 1.25 }}
      >
        <Sparkles size={18} color="var(--oxygen-palette-primary-main, currentColor)" />
        <Typography variant="body2" sx={{ fontWeight: 600, flexGrow: 1 }}>
          Agent
        </Typography>
        {participants.length > 0 && (
          <AvatarGroup
            max={4}
            sx={{
              mr: 0.5,
              "& .MuiAvatar-root": { width: 24, height: 24, fontSize: "0.7rem" },
            }}
          >
            {participants.map((p) => (
              <Tooltip key={p.id} title={p.displayName}>
                <Avatar sx={{ bgcolor: p.isOwn ? "primary.main" : "info.main" }}>
                  {initialOf(p.displayName)}
                </Avatar>
              </Tooltip>
            ))}
          </AvatarGroup>
        )}
        <Tooltip title="New conversation">
          <span>
            <IconButton
              size="small"
              aria-label="New conversation"
              disabled={isSending}
              onClick={onNewConversation}
            >
              <SquarePen size={16} />
            </IconButton>
          </span>
        </Tooltip>
        <Tooltip title="Open spec workspace">
          <IconButton size="small" aria-label="Open spec workspace" onClick={openSpec}>
            <ExternalLink size={16} />
          </IconButton>
        </Tooltip>
        <IconButton size="small" aria-label="Close agent chat" onClick={onClose}>
          <XIcon size={16} />
        </IconButton>
      </Stack>
      <Divider />

      {/* Feed */}
      <Box ref={scrollRef} sx={{ flexGrow: 1, overflow: "auto", p: 2 }}>
        <Box ref={contentRef}>
          {feed.length === 0 ? (
            <Stack
              spacing={2}
              sx={{ alignItems: "center", textAlign: "center", mt: 5, px: 1 }}
            >
              <Avatar sx={{ width: 48, height: 48, bgcolor: "primary.main" }}>
                <Sparkles size={24} />
              </Avatar>
              <Typography variant="subtitle2">Hi! I&apos;m your Agent.</Typography>
              <Typography variant="body2" color="text.secondary">
                Ask me to edit this project&apos;s spec — I join the shared
                workspace and you can watch the files change live.
              </Typography>
              <Stack
                direction="row"
                spacing={1}
                useFlexGap
                sx={{ flexWrap: "wrap", justifyContent: "center" }}
              >
                {SUGGESTIONS.map((s) => (
                  <Chip
                    key={s}
                    label={s}
                    variant="outlined"
                    size="small"
                    onClick={() => setDraft(s)}
                    sx={{ cursor: "pointer" }}
                  />
                ))}
              </Stack>
            </Stack>
          ) : (
            <MessageList
              feed={feed}
              expandedGroups={expandedGroups}
              onToggleGroup={toggleGroup}
              onOpenSpec={openSpec}
              showWorkingTail={showWorkingTail}
            />
          )}
        </Box>
      </Box>

      {/* Composer */}
      <ChatInput
        value={draft}
        onChange={setDraft}
        onSubmit={submit}
        disabled={inputDisabled}
        contextLabel={displayName ?? projectName}
        hint={hint}
      />
    </Box>
  );
}
