// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/wso2/aep/aep-api/internal/clients/openchoreo"
)

// Ensure, that ProjectCellClientMock does implement openchoreo.ProjectCellClient.
// If this is not the case, regenerate this file with moq.
var _ openchoreo.ProjectCellClient = &ProjectCellClientMock{}

// ProjectCellClientMock is a mock implementation of openchoreo.ProjectCellClient.
//
//	func TestSomethingThatUsesProjectCellClient(t *testing.T) {
//
//		// make and configure a mocked openchoreo.ProjectCellClient
//		mockedProjectCellClient := &ProjectCellClientMock{
//			EnsureProjectReleaseBindingFunc: func(ctx context.Context, namespace string, projectName string, environment string) error {
//				panic("mock out the EnsureProjectReleaseBinding method")
//			},
//			ListPipelineNamesFunc: func(ctx context.Context, namespace string) ([]string, error) {
//				panic("mock out the ListPipelineNames method")
//			},
//			PipelineEnvironmentsFunc: func(ctx context.Context, namespace string, pipelineName string) ([]string, error) {
//				panic("mock out the PipelineEnvironments method")
//			},
//			ProjectReadinessFunc: func(ctx context.Context, namespace string, projectName string) (openchoreo.Readiness, error) {
//				panic("mock out the ProjectReadiness method")
//			},
//			ProjectReleaseBindingReadinessFunc: func(ctx context.Context, namespace string, projectName string, environment string) (openchoreo.Readiness, error) {
//				panic("mock out the ProjectReleaseBindingReadiness method")
//			},
//		}
//
//		// use mockedProjectCellClient in code that requires openchoreo.ProjectCellClient
//		// and then make assertions.
//
//	}
type ProjectCellClientMock struct {
	// EnsureProjectReleaseBindingFunc mocks the EnsureProjectReleaseBinding method.
	EnsureProjectReleaseBindingFunc func(ctx context.Context, namespace string, projectName string, environment string) error

	// ListPipelineNamesFunc mocks the ListPipelineNames method.
	ListPipelineNamesFunc func(ctx context.Context, namespace string) ([]string, error)

	// PipelineEnvironmentsFunc mocks the PipelineEnvironments method.
	PipelineEnvironmentsFunc func(ctx context.Context, namespace string, pipelineName string) ([]string, error)

	// ProjectReadinessFunc mocks the ProjectReadiness method.
	ProjectReadinessFunc func(ctx context.Context, namespace string, projectName string) (openchoreo.Readiness, error)

	// ProjectReleaseBindingReadinessFunc mocks the ProjectReleaseBindingReadiness method.
	ProjectReleaseBindingReadinessFunc func(ctx context.Context, namespace string, projectName string, environment string) (openchoreo.Readiness, error)

	// calls tracks calls to the methods.
	calls struct {
		// EnsureProjectReleaseBinding holds details about calls to the EnsureProjectReleaseBinding method.
		EnsureProjectReleaseBinding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// ProjectName is the projectName argument value.
			ProjectName string
			// Environment is the environment argument value.
			Environment string
		}
		// ListPipelineNames holds details about calls to the ListPipelineNames method.
		ListPipelineNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
		}
		// PipelineEnvironments holds details about calls to the PipelineEnvironments method.
		PipelineEnvironments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// PipelineName is the pipelineName argument value.
			PipelineName string
		}
		// ProjectReadiness holds details about calls to the ProjectReadiness method.
		ProjectReadiness []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// ProjectName is the projectName argument value.
			ProjectName string
		}
		// ProjectReleaseBindingReadiness holds details about calls to the ProjectReleaseBindingReadiness method.
		ProjectReleaseBindingReadiness []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// ProjectName is the projectName argument value.
			ProjectName string
			// Environment is the environment argument value.
			Environment string
		}
	}
	lockEnsureProjectReleaseBinding    sync.RWMutex
	lockListPipelineNames              sync.RWMutex
	lockPipelineEnvironments           sync.RWMutex
	lockProjectReadiness               sync.RWMutex
	lockProjectReleaseBindingReadiness sync.RWMutex
}

// EnsureProjectReleaseBinding calls EnsureProjectReleaseBindingFunc.
func (mock *ProjectCellClientMock) EnsureProjectReleaseBinding(ctx context.Context, namespace string, projectName string, environment string) error {
	if mock.EnsureProjectReleaseBindingFunc == nil {
		panic("ProjectCellClientMock.EnsureProjectReleaseBindingFunc: method is nil but ProjectCellClient.EnsureProjectReleaseBinding was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Namespace   string
		ProjectName string
		Environment string
	}{
		Ctx:         ctx,
		Namespace:   namespace,
		ProjectName: projectName,
		Environment: environment,
	}
	mock.lockEnsureProjectReleaseBinding.Lock()
	mock.calls.EnsureProjectReleaseBinding = append(mock.calls.EnsureProjectReleaseBinding, callInfo)
	mock.lockEnsureProjectReleaseBinding.Unlock()
	return mock.EnsureProjectReleaseBindingFunc(ctx, namespace, projectName, environment)
}

// EnsureProjectReleaseBindingCalls gets all the calls that were made to EnsureProjectReleaseBinding.
// Check the length with:
//
//	len(mockedProjectCellClient.EnsureProjectReleaseBindingCalls())
func (mock *ProjectCellClientMock) EnsureProjectReleaseBindingCalls() []struct {
	Ctx         context.Context
	Namespace   string
	ProjectName string
	Environment string
} {
	var calls []struct {
		Ctx         context.Context
		Namespace   string
		ProjectName string
		Environment string
	}
	mock.lockEnsureProjectReleaseBinding.RLock()
	calls = mock.calls.EnsureProjectReleaseBinding
	mock.lockEnsureProjectReleaseBinding.RUnlock()
	return calls
}

// ListPipelineNames calls ListPipelineNamesFunc.
func (mock *ProjectCellClientMock) ListPipelineNames(ctx context.Context, namespace string) ([]string, error) {
	if mock.ListPipelineNamesFunc == nil {
		panic("ProjectCellClientMock.ListPipelineNamesFunc: method is nil but ProjectCellClient.ListPipelineNames was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
	}{
		Ctx:       ctx,
		Namespace: namespace,
	}
	mock.lockListPipelineNames.Lock()
	mock.calls.ListPipelineNames = append(mock.calls.ListPipelineNames, callInfo)
	mock.lockListPipelineNames.Unlock()
	return mock.ListPipelineNamesFunc(ctx, namespace)
}

// ListPipelineNamesCalls gets all the calls that were made to ListPipelineNames.
// Check the length with:
//
//	len(mockedProjectCellClient.ListPipelineNamesCalls())
func (mock *ProjectCellClientMock) ListPipelineNamesCalls() []struct {
	Ctx       context.Context
	Namespace string
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
	}
	mock.lockListPipelineNames.RLock()
	calls = mock.calls.ListPipelineNames
	mock.lockListPipelineNames.RUnlock()
	return calls
}

// PipelineEnvironments calls PipelineEnvironmentsFunc.
func (mock *ProjectCellClientMock) PipelineEnvironments(ctx context.Context, namespace string, pipelineName string) ([]string, error) {
	if mock.PipelineEnvironmentsFunc == nil {
		panic("ProjectCellClientMock.PipelineEnvironmentsFunc: method is nil but ProjectCellClient.PipelineEnvironments was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Namespace    string
		PipelineName string
	}{
		Ctx:          ctx,
		Namespace:    namespace,
		PipelineName: pipelineName,
	}
	mock.lockPipelineEnvironments.Lock()
	mock.calls.PipelineEnvironments = append(mock.calls.PipelineEnvironments, callInfo)
	mock.lockPipelineEnvironments.Unlock()
	return mock.PipelineEnvironmentsFunc(ctx, namespace, pipelineName)
}

// PipelineEnvironmentsCalls gets all the calls that were made to PipelineEnvironments.
// Check the length with:
//
//	len(mockedProjectCellClient.PipelineEnvironmentsCalls())
func (mock *ProjectCellClientMock) PipelineEnvironmentsCalls() []struct {
	Ctx          context.Context
	Namespace    string
	PipelineName string
} {
	var calls []struct {
		Ctx          context.Context
		Namespace    string
		PipelineName string
	}
	mock.lockPipelineEnvironments.RLock()
	calls = mock.calls.PipelineEnvironments
	mock.lockPipelineEnvironments.RUnlock()
	return calls
}

// ProjectReadiness calls ProjectReadinessFunc.
func (mock *ProjectCellClientMock) ProjectReadiness(ctx context.Context, namespace string, projectName string) (openchoreo.Readiness, error) {
	if mock.ProjectReadinessFunc == nil {
		panic("ProjectCellClientMock.ProjectReadinessFunc: method is nil but ProjectCellClient.ProjectReadiness was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Namespace   string
		ProjectName string
	}{
		Ctx:         ctx,
		Namespace:   namespace,
		ProjectName: projectName,
	}
	mock.lockProjectReadiness.Lock()
	mock.calls.ProjectReadiness = append(mock.calls.ProjectReadiness, callInfo)
	mock.lockProjectReadiness.Unlock()
	return mock.ProjectReadinessFunc(ctx, namespace, projectName)
}

// ProjectReadinessCalls gets all the calls that were made to ProjectReadiness.
// Check the length with:
//
//	len(mockedProjectCellClient.ProjectReadinessCalls())
func (mock *ProjectCellClientMock) ProjectReadinessCalls() []struct {
	Ctx         context.Context
	Namespace   string
	ProjectName string
} {
	var calls []struct {
		Ctx         context.Context
		Namespace   string
		ProjectName string
	}
	mock.lockProjectReadiness.RLock()
	calls = mock.calls.ProjectReadiness
	mock.lockProjectReadiness.RUnlock()
	return calls
}

// ProjectReleaseBindingReadiness calls ProjectReleaseBindingReadinessFunc.
func (mock *ProjectCellClientMock) ProjectReleaseBindingReadiness(ctx context.Context, namespace string, projectName string, environment string) (openchoreo.Readiness, error) {
	if mock.ProjectReleaseBindingReadinessFunc == nil {
		panic("ProjectCellClientMock.ProjectReleaseBindingReadinessFunc: method is nil but ProjectCellClient.ProjectReleaseBindingReadiness was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Namespace   string
		ProjectName string
		Environment string
	}{
		Ctx:         ctx,
		Namespace:   namespace,
		ProjectName: projectName,
		Environment: environment,
	}
	mock.lockProjectReleaseBindingReadiness.Lock()
	mock.calls.ProjectReleaseBindingReadiness = append(mock.calls.ProjectReleaseBindingReadiness, callInfo)
	mock.lockProjectReleaseBindingReadiness.Unlock()
	return mock.ProjectReleaseBindingReadinessFunc(ctx, namespace, projectName, environment)
}

// ProjectReleaseBindingReadinessCalls gets all the calls that were made to ProjectReleaseBindingReadiness.
// Check the length with:
//
//	len(mockedProjectCellClient.ProjectReleaseBindingReadinessCalls())
func (mock *ProjectCellClientMock) ProjectReleaseBindingReadinessCalls() []struct {
	Ctx         context.Context
	Namespace   string
	ProjectName string
	Environment string
} {
	var calls []struct {
		Ctx         context.Context
		Namespace   string
		ProjectName string
		Environment string
	}
	mock.lockProjectReleaseBindingReadiness.RLock()
	calls = mock.calls.ProjectReleaseBindingReadiness
	mock.lockProjectReleaseBindingReadiness.RUnlock()
	return calls
}
