// Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package agentfold

// End-to-end op parity against the REAL @aep/agent-stream FileBundle:
// testdata/frontmatter_bundle.json (generated by testdata/gen/
// gen-frontmatter.mjs from the dist build) records one op per case with the
// TS OpResult and the post-op content. The Fold must reproduce the content
// byte-for-byte and the result's ok/status/code; "UNSUPPORTED-" cases (ops TS
// applies but whose bytes are outside the yamlemit subset) must fail loudly.

import (
	"context"
	"encoding/json"
	"errors"
	"os"
	"strings"
	"testing"
)

type bundleCase struct {
	Name    string          `json:"name"`
	Path    string          `json:"path"`
	Op      string          `json:"op"`
	Content *string         `json:"content"` // nil for add cases (empty seed)
	Args    json.RawMessage `json:"args"`
	Result  struct {
		OK     bool   `json:"ok"`
		Status string `json:"status"`
		Code   string `json:"code"`
	} `json:"result"`
	After *string `json:"after"` // nil = path absent after the op
}

func TestFrontmatterAndGuard_MatchFileBundleFixture(t *testing.T) {
	t.Skip("DISABLED pending fixture migration to the dependencies[] schema " +
		"(dependency-management follow-up): testdata/frontmatter_bundle.json uses the pre-Phase-3 " +
		"connections[] schema. See docs/design/dependency-management-migration.md §8 (Phase-6 e2e Bug A).")
	raw, err := os.ReadFile("testdata/frontmatter_bundle.json")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var cases []bundleCase
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatalf("decode fixture: %v", err)
	}
	if len(cases) < 30 {
		t.Fatalf("suspiciously small fixture: %d cases", len(cases))
	}
	ctx := context.Background()

	for _, c := range cases {
		t.Run(c.Name, func(t *testing.T) {
			seed := map[string]string{}
			if c.Content != nil {
				seed[c.Path] = *c.Content
			}
			fold := NewFromSnapshot(seed)

			var args []any
			dec := json.NewDecoder(strings.NewReader(string(c.Args)))
			dec.UseNumber()
			if err := dec.Decode(&args); err != nil {
				t.Fatalf("decode args: %v", err)
			}

			var res OpResult
			var opErr error
			switch c.Op {
			case "frontmatter":
				key := args[0].(string)
				value, ok := asFrontmatterValue(args[1])
				if !ok {
					t.Fatalf("fixture value not a frontmatter value: %v", args[1])
				}
				res, opErr = fold.SetFrontmatterField(ctx, c.Path, key, value)
			case "add":
				res, opErr = fold.AddFile(ctx, c.Path, args[0].(string))
			case "edit":
				res, opErr = fold.EditFile(ctx, c.Path, args[0].(string), args[1].(string))
			default:
				t.Fatalf("unknown op %q", c.Op)
			}

			if strings.HasPrefix(c.Name, "UNSUPPORTED-") {
				var ue *UnsupportedFrontmatterError
				if !errors.As(opErr, &ue) {
					t.Fatalf("want UnsupportedFrontmatterError, got err=%v res=%+v", opErr, res)
				}
				if ue.Path != c.Path {
					t.Errorf("error path = %q, want %q", ue.Path, c.Path)
				}
				return
			}
			if opErr != nil {
				t.Fatalf("op error: %v", opErr)
			}
			if res.OK != c.Result.OK {
				t.Fatalf("ok = %v, want %v (res %+v)", res.OK, c.Result.OK, res)
			}
			if res.OK && string(res.Status) != c.Result.Status {
				t.Errorf("status = %q, want %q", res.Status, c.Result.Status)
			}
			if !res.OK && string(res.Code) != c.Result.Code {
				t.Errorf("code = %q, want %q (message %q)", res.Code, c.Result.Code, res.Message)
			}

			state := fold.FullState(seed)
			got, exists := state[c.Path]
			if c.After == nil {
				if exists {
					t.Fatalf("path %q should be absent, has %q", c.Path, got)
				}
				return
			}
			if !exists {
				t.Fatalf("path %q missing, want %q", c.Path, *c.After)
			}
			if got != *c.After {
				t.Fatalf("content divergence from FileBundle:\n got: %q\nwant: %q", got, *c.After)
			}
		})
	}
}
